-- ============================================================
-- Fix: Apply missing RLS policies and performance indexes
--
-- The migrations 20260224000000 and 20260224000001 failed in
-- production because:
--   1. 20260224000000 tried to create an index on
--      messaging_webhook_events.organization_id (column doesn't exist)
--   2. This caused the entire transaction to roll back, including
--      the get_user_org_id() function creation
--   3. 20260224000001 then failed because it depended on that function
--
-- Result: business_units table has no SELECT policy, returning 404
--
-- This migration re-applies everything, skipping the bad index.
-- ============================================================


-- ============================================================
-- SECTION 1: organization_id single-column indexes (HIGH priority)
-- Every table that is filtered/scanned by org at the RLS layer
-- must have this index or all multi-tenant queries degrade to
-- sequential scans on the full table.
-- ============================================================

-- activities.organization_id
CREATE INDEX IF NOT EXISTS idx_activities_organization_id
  ON public.activities(organization_id);

-- contacts.organization_id
CREATE INDEX IF NOT EXISTS idx_contacts_organization_id
  ON public.contacts(organization_id);

-- deals.organization_id
CREATE INDEX IF NOT EXISTS idx_deals_organization_id
  ON public.deals(organization_id);

-- leads.organization_id
CREATE INDEX IF NOT EXISTS idx_leads_organization_id
  ON public.leads(organization_id);

-- NOTE: Skipping idx_ai_decisions_organization_id because
-- ai_decisions doesn't have organization_id (uses user_id instead).
-- NOTE: Skipping idx_messaging_webhook_events_organization_id
-- because the column doesn't exist in that table. Use channel_id instead.


-- ============================================================
-- SECTION 2: Composite indexes for common filter patterns
-- These cover the two-column WHERE clauses most frequently
-- generated by the application — verified against the existing
-- query hooks in lib/query/hooks/.
-- ============================================================

-- contacts: filtered by org + stage (funnel/kanban list views)
-- Improves over the existing idx_contacts_stage (single-column)
-- when the RLS org filter is applied alongside.
CREATE INDEX IF NOT EXISTS idx_contacts_org_stage
  ON public.contacts(organization_id, stage);

-- contacts: filtered by org + status (active/inactive toggles)
-- Improves over the existing idx_contacts_status (single-column).
CREATE INDEX IF NOT EXISTS idx_contacts_org_status
  ON public.contacts(organization_id, status);

-- deals: filtered by org + board (pipeline view — most common query)
-- Complements the existing idx_deals_board_id with the org guard.
CREATE INDEX IF NOT EXISTS idx_deals_org_board
  ON public.deals(organization_id, board_id);

-- activities: filtered by org + ordered by date descending
-- Used in activity timelines and deal/contact detail views.
CREATE INDEX IF NOT EXISTS idx_activities_org_date
  ON public.activities(organization_id, date DESC);


-- ============================================================
-- SECTION 3: messaging_conversations status + last_message_at
-- The unified inbox query orders by last_message_at DESC and
-- filters by status (open/closed/pending). Without this index
-- the sort requires a full-table scan on a potentially large
-- table with high write throughput.
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_messaging_conversations_status_last_msg
  ON public.messaging_conversations(status, last_message_at DESC);


-- ============================================================
-- SECTION 4: Cached RLS org lookup helper
--
-- get_user_org_id() replaces inline subqueries of the form:
--   (SELECT organization_id FROM profiles WHERE id = auth.uid())
-- inside RLS policies.
--
-- STABLE + SECURITY DEFINER allows Postgres to cache the result
-- for the duration of a single SQL statement, so each multi-row
-- RLS check pays the profile lookup cost only once rather than
-- once per row.
--
-- Restricted to `authenticated` role only — anon and public
-- have no business calling this function.
-- ============================================================

CREATE OR REPLACE FUNCTION public.get_user_org_id()
RETURNS UUID
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT organization_id
  FROM public.profiles
  WHERE id = (SELECT auth.uid())
$$;

-- Lock down execution: strip default PUBLIC grant, then grant
-- only to authenticated users.
REVOKE ALL ON FUNCTION public.get_user_org_id() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_user_org_id() TO authenticated;

COMMENT ON FUNCTION public.get_user_org_id() IS
  'Returns the organization_id for the currently authenticated user. '
  'STABLE + SECURITY DEFINER enables per-statement result caching inside '
  'RLS policies, eliminating repeated profile lookups.';


-- ============================================================
-- SECTION 5: RLS Policies (from 20260224000001)
--
-- All policies now use get_user_org_id() for org isolation.
-- ============================================================

-- Table: activities
DROP POLICY IF EXISTS "activities_org_isolate" ON public.activities;
CREATE POLICY "activities_org_isolate" ON public.activities
  FOR ALL TO authenticated
  USING (organization_id = public.get_user_org_id())
  WITH CHECK (organization_id = public.get_user_org_id());


-- Table: boards
DROP POLICY IF EXISTS "boards_org_isolate" ON public.boards;
CREATE POLICY "boards_org_isolate" ON public.boards
  FOR ALL TO authenticated
  USING (organization_id = public.get_user_org_id())
  WITH CHECK (organization_id = public.get_user_org_id());


-- Table: board_stages
DROP POLICY IF EXISTS "board_stages_org_isolate" ON public.board_stages;
CREATE POLICY "board_stages_org_isolate" ON public.board_stages
  FOR ALL TO authenticated
  USING (organization_id = public.get_user_org_id())
  WITH CHECK (organization_id = public.get_user_org_id());


-- Table: contacts
DROP POLICY IF EXISTS "contacts_org_isolate" ON public.contacts;
CREATE POLICY "contacts_org_isolate" ON public.contacts
  FOR ALL TO authenticated
  USING (organization_id = public.get_user_org_id())
  WITH CHECK (organization_id = public.get_user_org_id());


-- Table: crm_companies
DROP POLICY IF EXISTS "crm_companies_org_isolate" ON public.crm_companies;
CREATE POLICY "crm_companies_org_isolate" ON public.crm_companies
  FOR ALL TO authenticated
  USING (organization_id = public.get_user_org_id())
  WITH CHECK (organization_id = public.get_user_org_id());


-- Table: custom_field_definitions
DROP POLICY IF EXISTS "custom_field_definitions_org_isolate" ON public.custom_field_definitions;
CREATE POLICY "custom_field_definitions_org_isolate" ON public.custom_field_definitions
  FOR ALL TO authenticated
  USING (organization_id = public.get_user_org_id())
  WITH CHECK (organization_id = public.get_user_org_id());


-- Table: deals
DROP POLICY IF EXISTS "deals_org_isolate" ON public.deals;
CREATE POLICY "deals_org_isolate" ON public.deals
  FOR ALL TO authenticated
  USING (organization_id = public.get_user_org_id())
  WITH CHECK (organization_id = public.get_user_org_id());


-- Table: deal_items
DROP POLICY IF EXISTS "deal_items_org_isolate" ON public.deal_items;
CREATE POLICY "deal_items_org_isolate" ON public.deal_items
  FOR ALL TO authenticated
  USING (organization_id = public.get_user_org_id())
  WITH CHECK (organization_id = public.get_user_org_id());


-- Table: leads
DROP POLICY IF EXISTS "leads_org_isolate" ON public.leads;
CREATE POLICY "leads_org_isolate" ON public.leads
  FOR ALL TO authenticated
  USING (organization_id = public.get_user_org_id())
  WITH CHECK (organization_id = public.get_user_org_id());


-- Table: products
DROP POLICY IF EXISTS "products_org_isolate" ON public.products;
CREATE POLICY "products_org_isolate" ON public.products
  FOR ALL TO authenticated
  USING (organization_id = public.get_user_org_id())
  WITH CHECK (organization_id = public.get_user_org_id());


-- Table: tags
DROP POLICY IF EXISTS "tags_org_isolate" ON public.tags;
CREATE POLICY "tags_org_isolate" ON public.tags
  FOR ALL TO authenticated
  USING (organization_id = public.get_user_org_id())
  WITH CHECK (organization_id = public.get_user_org_id());


-- Table: security_alerts
DROP POLICY IF EXISTS "security_alerts_org_select" ON public.security_alerts;
CREATE POLICY "security_alerts_org_select" ON public.security_alerts
  FOR SELECT TO authenticated
  USING (organization_id = public.get_user_org_id());


-- Table: audit_logs
DROP POLICY IF EXISTS "audit_logs_org_select" ON public.audit_logs;
CREATE POLICY "audit_logs_org_select" ON public.audit_logs
  FOR SELECT TO authenticated
  USING (organization_id = public.get_user_org_id());


-- Table: system_notifications
DROP POLICY IF EXISTS "system_notifications_org_isolate" ON public.system_notifications;
CREATE POLICY "system_notifications_org_isolate" ON public.system_notifications
  FOR ALL TO authenticated
  USING (organization_id = public.get_user_org_id())
  WITH CHECK (organization_id = public.get_user_org_id());


-- Table: contact_merge_log
DROP POLICY IF EXISTS "contact_merge_log_org_select" ON public.contact_merge_log;
CREATE POLICY "contact_merge_log_org_select" ON public.contact_merge_log
  FOR SELECT TO authenticated
  USING (organization_id = public.get_user_org_id());


-- Table: deal_activities
DROP POLICY IF EXISTS "deal_activities_org_select" ON public.deal_activities;
CREATE POLICY "deal_activities_org_select" ON public.deal_activities
  FOR SELECT TO authenticated
  USING (organization_id = public.get_user_org_id());

DROP POLICY IF EXISTS "deal_activities_org_insert" ON public.deal_activities;
CREATE POLICY "deal_activities_org_insert" ON public.deal_activities
  FOR INSERT TO authenticated
  WITH CHECK (organization_id = public.get_user_org_id());


-- Table: ai_feature_flags
DROP POLICY IF EXISTS "ai_feature_flags_select" ON public.ai_feature_flags;
CREATE POLICY "ai_feature_flags_select" ON public.ai_feature_flags
  FOR SELECT TO authenticated
  USING (organization_id = public.get_user_org_id());


-- Table: ai_prompt_templates
DROP POLICY IF EXISTS "ai_prompt_templates_select" ON public.ai_prompt_templates;
CREATE POLICY "ai_prompt_templates_select" ON public.ai_prompt_templates
  FOR SELECT TO authenticated
  USING (organization_id = public.get_user_org_id());


-- Table: ai_qualification_templates
DROP POLICY IF EXISTS "ai_qualification_templates_select" ON public.ai_qualification_templates;
CREATE POLICY "ai_qualification_templates_select" ON public.ai_qualification_templates
  FOR SELECT TO authenticated
  USING (
    is_system = true
    OR organization_id = public.get_user_org_id()
  );


-- Table: organization_invites
DROP POLICY IF EXISTS "organization_invites_select" ON public.organization_invites;
CREATE POLICY "organization_invites_select" ON public.organization_invites
  FOR SELECT TO authenticated
  USING (organization_id = public.get_user_org_id());


-- Table: organization_settings
DROP POLICY IF EXISTS "organization_settings_select" ON public.organization_settings;
CREATE POLICY "organization_settings_select" ON public.organization_settings
  FOR SELECT TO authenticated
  USING (organization_id = public.get_user_org_id());


-- Table: business_units (CRITICAL — this was missing!)
DROP POLICY IF EXISTS "business_units_select" ON public.business_units;
CREATE POLICY "business_units_select" ON public.business_units
  FOR SELECT TO authenticated
  USING (organization_id = public.get_user_org_id());


-- Table: lead_routing_rules
DROP POLICY IF EXISTS "lead_routing_rules_select" ON public.lead_routing_rules;
CREATE POLICY "lead_routing_rules_select" ON public.lead_routing_rules
  FOR SELECT TO authenticated
  USING (organization_id = public.get_user_org_id());


-- Table: messaging_channels
DROP POLICY IF EXISTS "messaging_channels_select" ON public.messaging_channels;
CREATE POLICY "messaging_channels_select" ON public.messaging_channels
  FOR SELECT TO authenticated
  USING (organization_id = public.get_user_org_id());


-- Table: stage_ai_config
DROP POLICY IF EXISTS "stage_ai_config_select" ON public.stage_ai_config;
CREATE POLICY "stage_ai_config_select" ON public.stage_ai_config
  FOR SELECT TO authenticated
  USING (organization_id = public.get_user_org_id());


-- ============================================================
-- SECTION 6: contacts.ai_paused column (from 20260406130000)
--
-- Migration 20260406130000 may not have been applied in all
-- environments. This ensures the column exists idempotently.
-- ============================================================

ALTER TABLE public.contacts
  ADD COLUMN IF NOT EXISTS ai_paused BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN public.contacts.ai_paused IS
  'When true, AI auto-responses are disabled for all conversations with this contact.';


-- ============================================================
-- SECTION 7: messaging_conversations RLS — simplified org check
--
-- The original policy "Users view conversations in accessible units"
-- requires business_unit_members membership, which excludes non-admin
-- users from seeing conversations unless they are explicitly assigned
-- to the conversation's business unit.
--
-- Replace with a simpler org-level policy so all authenticated users
-- in the organization can read conversations.
-- ============================================================

DROP POLICY IF EXISTS "Users view conversations in accessible units" ON public.messaging_conversations;
DROP POLICY IF EXISTS "messaging_conversations_select" ON public.messaging_conversations;
CREATE POLICY "messaging_conversations_select" ON public.messaging_conversations
  FOR SELECT TO authenticated
  USING (organization_id = public.get_user_org_id());

DROP POLICY IF EXISTS "Users update conversations they can access" ON public.messaging_conversations;
DROP POLICY IF EXISTS "messaging_conversations_update" ON public.messaging_conversations;
CREATE POLICY "messaging_conversations_update" ON public.messaging_conversations
  FOR UPDATE TO authenticated
  USING (organization_id = public.get_user_org_id())
  WITH CHECK (organization_id = public.get_user_org_id());

DROP POLICY IF EXISTS "System can insert conversations" ON public.messaging_conversations;
DROP POLICY IF EXISTS "messaging_conversations_insert" ON public.messaging_conversations;
CREATE POLICY "messaging_conversations_insert" ON public.messaging_conversations
  FOR INSERT TO authenticated
  WITH CHECK (organization_id = public.get_user_org_id());

DROP POLICY IF EXISTS "messaging_conversations_delete" ON public.messaging_conversations;
CREATE POLICY "messaging_conversations_delete" ON public.messaging_conversations
  FOR DELETE TO authenticated
  USING (organization_id = public.get_user_org_id());
